// import type { Metadata } from 'next'
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import { AnimatePresence, motion } from 'framer-motion';
import Loader from '../components/loader'
import { useAnimationStore } from '@/store/loader';



const inter = Inter({ subsets: ['latin'] })


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const { animationComplete } = useAnimationStore();
 
  return (
    <html lang="en">
      <body className={`${inter.className} relative body-bg `}>
        <div className='absolute w-full h-full pattern-dots pattern-opacity-10 pattern-bg-transparent pattern-size-2 pattern-gray-100'>
        </div>
        <AnimatePresence mode='wait'>
          {!animationComplete ? (
            <motion.div key='loader' className='flex items-center justify-center w-full h-screen'>
              <Loader />
            </motion.div>
          ) : (
            <main>
              {children}
            </main>
          )}
        </AnimatePresence>
      </body>
    </html>
  )
}
