
'use client'
import './globals.css'

import { Poppins } from 'next/font/google'
import { AnimatePresence, motion } from 'framer-motion';
import Loader from '../components/loader'
import { useAnimationStore } from '@/store/loader';
import Navbar from '@/components/shared/navbar';

// import type { Metadata } from 'next'
// export const metadata: Metadata = {
//   title: 'NEXA',
//   description: 'Welcome to Nexa, your ultimate destination for AI toolkits that empower users and developers to harness the potential of artificial intelligence. With Nexa, you will find a curated collection of AI resources, ready to be integrated into your projects, all in one place. Generated by create next app',
// }


const poppins = Poppins({
  subsets: ['latin-ext'],
  style: 'normal',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const { animationComplete } = useAnimationStore();
 
  return (
    <html lang="en">
      <body className={`${poppins.className} font-poppins relative body-bg `}>
        <div className='absolute w-full h-full -z-10 pattern-dots pattern-opacity-10 pattern-bg-transparent pattern-size-2 pattern-gray-100'>
        </div>
        <AnimatePresence mode='wait'>
          {!animationComplete ? (
            <motion.div key='loader' className='flex items-center justify-center w-full h-screen'>
              <Loader />
            </motion.div>
          ) : (
            <>
            <Navbar />
            <main className='items-center justify-center w-full h-full inner'>
              {children}
            </main>
            </>
          )}
        </AnimatePresence>
      </body>
    </html>
  )
}
